//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Checks
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CheckNumber { get; set; }
        public Nullable<double> FullPrice { get; set; }
        public Nullable<int> Count { get; set; }
        public Nullable<System.DateTime> DateTimeCheck { get; set; }
    
        public virtual Orders Orders { get; set; }
    }
}
