//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class Deliveries
    {
        public int Id { get; set; }
        public Nullable<int> OrderId { get; set; }
        public Nullable<int> CourierId { get; set; }
        public string StatusDelivery { get; set; }
        public Nullable<System.DateTime> DateTimeDelivery { get; set; }
    
        public virtual Couriers Couriers { get; set; }
        public virtual Orders Orders { get; set; }
    }
}
