//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryTest
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class MusicalInstrumentShopEntities1 : DbContext
    {
        private static MusicalInstrumentShopEntities1 _context;
        public MusicalInstrumentShopEntities1()
            : base("name=MusicalInstrumentShopEntities1")
        {
        }

        public static MusicalInstrumentShopEntities1 GetContext()
        {
            if( _context == null )
                _context = new MusicalInstrumentShopEntities1();
            return _context;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Categories> Categories { get; set; }
        public virtual DbSet<Checks> Checks { get; set; }
        public virtual DbSet<CourierInvoices> CourierInvoices { get; set; }
        public virtual DbSet<Couriers> Couriers { get; set; }
        public virtual DbSet<Customers> Customers { get; set; }
        public virtual DbSet<Deliveries> Deliveries { get; set; }
        public virtual DbSet<Orders> Orders { get; set; }
        public virtual DbSet<Products> Products { get; set; }
        public virtual DbSet<StorageRooms> StorageRooms { get; set; }
        public virtual DbSet<sysdiagrams> sysdiagrams { get; set; }
    }
}
