//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DeliveryTest
{
    using System;
    using System.Collections.Generic;
    
    public partial class StorageRooms
    {
        public int Id { get; set; }
        public Nullable<int> ProductId { get; set; }
        public string Status { get; set; }
        public string Address { get; set; }
    
        public virtual Products Products { get; set; }
    }
}
